version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventSemOneStackJS"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1o8mj0e61cpta"
s3_prefix = "eventSemOneStackJS"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
