AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  lambdaSQSHandler:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 130
      Timeout: 30
      Policies:
      # Read more about SAM policy templates here
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
       - AWSLambdaExecute
       - DynamoDBCrudPolicy:
          TableName: !Ref MyDynamoDBTableJS
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTableJS
      Events:
        Trigger:
          Type: SQS
          Properties:
            Queue: !GetAtt sqsToLambdaToDyno.Arn
            BatchSize: 10

            
  MyDynamoDBTableJS:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: MyDynamoDBTableJS
      KeySchema:
        - AttributeName: accountId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: accountId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      ProvisionedThroughput:
        ReadCapacityUnits: 0
        WriteCapacityUnits: 0
  
  sqsToLambdaToDyno:
    Type: AWS::SQS::Queue
